# Generated by Django 4.2.9 on 2024-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
