# Generated by Django 4.2.9 on 2024-01-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='activated_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.service'),
        ),
    ]
